/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-12-07 12:01:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/dearj/workspace_all/pet/pet_1128/pet_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/petProject_1110/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/dearj/workspace_all/pet/pet_1128/pet_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/petProject_1110/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/member/../include/header.jsp", Long.valueOf(1670408248823L));
    _jspx_dependants.put("/WEB-INF/views/member/../include/footer.jsp", Long.valueOf(1669639196437L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1640854084188L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>welcome pet</title>\r\n");
      out.write("<script>\r\n");
      out.write("function go_search() {\r\n");
      out.write("	var theForm = document.frm;\r\n");
      out.write("	theForm.action = \"MypetServlet?command=search\";\r\n");
      out.write("	theForm.submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"/resources/css/mypet.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form name=\"frm\" method=\"post\">\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("		<header>\r\n");
      out.write("			<div id=\"catagory_menu\">\r\n");
      out.write("				<ul class=\"right_menu\">\r\n");
      out.write("					");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<li><a href=\"/mypage/cartList\">장바구니</a></li>\r\n");
      out.write("					<li><a href=\"MypetServlet?command=mypage\">마이페이지</a></li>\r\n");
      out.write("					<li><a href=\"MypetServlet?command=qna_list\">고객센터</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div id=\"logo\">\r\n");
      out.write("				<a href=\"/\"> \r\n");
      out.write("				<img src=\"/resources/images/logo.jpg\">\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"search_area\">\r\n");
      out.write("				<div class=\"search_form\">\r\n");
      out.write("					<input type=\"text\" name=\"searchValue\" class=\"searchTerm\" placeholder=\"원하는 상품을 검색해보세요.\"> \r\n");
      out.write("					<button class=\"searchButton\" type=\"submit\" name=\"btn_search\" value=\"검색\" onClick=\"go_search()\">\r\n");
      out.write("						<i class=\"search\"></i>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"aa\">\r\n");
      out.write("				<div class=\"top_box\">\r\n");
      out.write("					<a href=\"/cate_main?cateName=dog\" class=\"dog_box\">강아지</a> \r\n");
      out.write("					<a href=\"/cate_main?cateName=cat\" class=\"cat_box\">고양이</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"bottom_box\">\r\n");
      out.write("					<a href=\"/cate_main?cateName=bird\" class=\"bird_box\">조류</a> \r\n");
      out.write("					<a href=\"/cate_main?cateName=rep\" class=\"rep_box\">파충류</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("		</header>\r\n");
      out.write("	</div>\r\n");
      out.write("</form>");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/member.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<article>\r\n");
      out.write("	<h2>회원가입</h2>\r\n");
      out.write("	<form  method=\"post\" name=\"formm\">\r\n");
      out.write("		<fieldset id=\"join_field\">\r\n");
      out.write("			<table id=\"join_table\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>아이디</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"id\" id=\"id\" size=\"12\"></td>\r\n");
      out.write("					<td><input type=\"hidden\" name=\"reid\">\r\n");
      out.write("					   <!--  <input type=\"button\" value=\"중복 체크\" onclick=\"idcheck()\" id=\"overlap\"\r\n");
      out.write("					        style=\"width:80px; height:35px;\"></td> -->\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>비밀번호</th>\r\n");
      out.write("					<td colspan='2'><input type=\"password\" name=\"password\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>비밀번호 확인</th>\r\n");
      out.write("					<td colspan='2'><input type=\"password\" name=\"passwordCheck\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>이름</th>\r\n");
      out.write("					<td colspan='2'><input type=\"text\" name=\"name\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr id=\"email_type\">\r\n");
      out.write("					<th>이메일 주소</th>\r\n");
      out.write("						<td colspan='2'><input type=\"text\" name=\"email\">\r\n");
      out.write("						<div style=\"display:none\" id=\"w\">\r\n");
      out.write("							<input type=\"text\" name=\"we\" style=\"margin-top: 0px; margin-bottom: 0px;\"></div>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>생년월일</th>\r\n");
      out.write("					<td colspan='2'><input type=\"text\" name=\"birthday\" placeholder=\"19900101\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr id=\"phone_type\">\r\n");
      out.write("					<th>휴대폰 번호</th>\r\n");
      out.write("					<td colspan='2'>\r\n");
      out.write("					<div id=\"phone_div\"><input type=\"text\" name=\"phone\"></div></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>주소</th>\r\n");
      out.write("					<td colspan='2'><input type=\"text\" name=\"address\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>관심사</th>\r\n");
      out.write("						<td colspan='2'>\r\n");
      out.write("						    <label><input type =\"radio\" name =\"cateName\" value =\"none\">관심없음</label>\r\n");
      out.write("						    <label><input type =\"radio\" name =\"cateName\" value =\"dog\">강아지</label>\r\n");
      out.write("						    <label><input type =\"radio\" name =\"cateName\" value =\"cat\">고양이</label>\r\n");
      out.write("						    <label><input type =\"radio\" name =\"cateName\" value =\"bird\">조류</label>\r\n");
      out.write("						    <label><input type =\"radio\" name =\"cateName\" value =\"rep\">파충류</label></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</fieldset>\r\n");
      out.write("		<div class=\"clear\"></div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<input type=\"button\" value=\"이전 페이지\" id=\"back\" onclick=\"history.go(-1)\">\r\n");
      out.write("			<input type=\"reset\" value=\"지우기\" id=\"join_cancle\">\r\n");
      out.write("			<input type=\"button\" value=\"회원가입\" onclick=\"go_save()\" id=\"join_ok\">\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("</article>\r\n");
      out.write("\r\n");
      out.write("<link href=\"/resources/css/mypet.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("a:hover{\r\n");
      out.write("text-decoration: none;\r\n");
      out.write("color: black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("	<footer>\r\n");
      out.write("\r\n");
      out.write("		<div>\r\n");
      out.write("			⊙ Copyright(c)2022 by Team웰컴펫</a>. All pictures cannot be copied without\r\n");
      out.write("			permission.<br> Contact mail : WelcomePet@mypet.com Tel : +82\r\n");
      out.write("			10-1234-5678\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("						");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/member/../include/header.jsp(26,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.member}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<li><a href=\"/member/login.do\">로그인</a></li>\r\n");
          out.write("\r\n");
          out.write("							<li><a href=\"/member/contract\">회원가입</a></li>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<li style=\"color: orange; transform:translateY(-10px)\">\r\n");
          out.write("								");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.member.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('님');
          out.write('(');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.member.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")</li>\r\n");
          out.write("							<li><a href=\"/member/logout.do\">로그아웃</a></li>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
